name: booking-system

services:
  redis:
    image: redis:8.6-alpine
    container_name: booking_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    # 1. Replace the 'image:' line with this build block
    build:
      context: .
      dockerfile: Dockerfile.postgres
      
    container_name: booking_postgres # (Use booking_postgres_prod for the prod file)
    restart: unless-stopped
    ports:
      - "${DATABASE_LOCAL_PORT:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      
    # 2. Update the command to preload the library and set the cron database
    command: >
      postgres 
      -c "max_connections=200" 
      -c "shared_preload_libraries=pg_cron" 
      -c "cron.database_name=${DATABASE_NAME}"
      -c "cron.use_background_workers=on"
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.3.1-management-alpine
    container_name: booking_rabbitmq
    restart: unless-stopped
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  node-app:
    container_name: booking-api
    build:
      context: .
      target: development
    profiles: [fullstack]
    volumes:
      - ./src:/app/src
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      PORT: ${PORT:-3000}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: booking_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
  rabbitmq_data:
