export enum AuditAction {
  FLIGHT_BOOKING_CREATED = 'FLIGHT_BOOKING_CREATED',
  FLIGHT_BOOKING_CANCELED = 'FLIGHT_BOOKING_CANCELED',
  HOTEL_BOOKING_CREATED = 'HOTEL_BOOKING_CREATED',
  HOTEL_BOOKING_CANCELED = 'HOTEL_BOOKING_CANCELED',
}
