export enum AuditAction {
  // ── Bookings ──────────────────────────────────────────────────────────────
  FLIGHT_BOOKING_CREATED  = 'FLIGHT_BOOKING_CREATED',
  FLIGHT_BOOKING_UPDATED  = 'FLIGHT_BOOKING_UPDATED',
  FLIGHT_BOOKING_CANCELED = 'FLIGHT_BOOKING_CANCELED',
  HOTEL_BOOKING_CREATED   = 'HOTEL_BOOKING_CREATED',
  HOTEL_BOOKING_UPDATED   = 'HOTEL_BOOKING_UPDATED',
  HOTEL_BOOKING_CANCELED  = 'HOTEL_BOOKING_CANCELED',
  // ── Transactions / Payment ────────────────────────────────────────────────
  TRANSACTION_CREATED      = 'TRANSACTION_CREATED',
  PAYMENT_INITIATED        = 'PAYMENT_INITIATED',
  PAYMENT_CAPTURED         = 'PAYMENT_CAPTURED',
  PAYMENT_FAILED           = 'PAYMENT_FAILED',
  PAYMENT_WEBHOOK_RECEIVED = 'PAYMENT_WEBHOOK_RECEIVED',
  TRANSACTION_CANCELED     = 'TRANSACTION_CANCELED',
}
